services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 9090:8080
  
  database:
    container_name: database
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: crm